### ISSUE TITLE
AttributeError: 'VAE' object has no attribute 'latent_frequency_bins'

### ISSUE THREAD

**Issue by Vmars666** [triXope/ComfyUI-triXope#1]
error after updated comfy ui.

both node pack and comfy ui up to date.

!!! Exception during processing !!! 'VAE' object has no attribute 'latent_frequency_bins'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 534, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 334, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 308, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 296, in process_inputs
    result = f(**inputs)
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-triXope-master\filmauteur_ltxv.py", line 649, in process
    audio_freq = audio_vae.latent_frequency_bins
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VAE' object has no attribute 'latent_frequency_bins'

**Comment by triXope** [comment]
I'm unable to reproduce this error. Are you using the correct Audio VAE and loader? Try the VAE loader from KJ nodes and the VAE from [https://huggingface.co/Kijai/LTX2.3_comfy/tree/main/vae](https://huggingface.co/Kijai/LTX2.3_comfy/tree/main/vae). Also, if you have KJ nodes installed, be sure it's also updated to the latest version.

**Comment by Vmars666** [comment]
thanks for the fast answer.  it was working fine before comfy ui update. the vae is good and kj node to.

i've check it all but still not working, 
so i strip the workflow to the minimum and  problem is still here.
only the audio vae is the problem. (it works with a standard ltxv 2.3 worlflow)
apparently they changed something in the way vae are cached in comfyui in the last update.

thanks again for this great node !



<img width="1276" height="989" alt="Image" src="https://github.com/user-attachments/assets/623f7cbf-dcba-4a73-9d0c-e8347865c6ac" />

**Comment by triXope** [comment]
Thank you for that info. I'll look into it further and get back to you asap.

**Comment by triXope** [comment]
I looked into and confirmed the issue. And of course, once I resolved the issue with the audio vae, I ran into a slew of other issues, either due directly to the latest updates, or stemmed from, haha, but it's all sorted out now, finally.

I've updated the Film Auteur (LTXV) node to conform to the changes in the latest ComfyUI update and all should be working now. Please git pull the repo to apply the latest updates. You may need to delete and re-add the node to your workflow to ensure a clean slate. Please let me know if you experience any other issues.

**Comment by Vmars666** [comment]
works fine now , all good !! thanks

**Comment by Vmars666** [comment]
sorry to reopen the issue  but after new update  there is a sound issue , sounds is played  slow motion, probably a frame rated difference between sound and video output. (basic worflow, t2v)

**Comment by triXope** [comment]
Thank you for letting me know. I'll take a look when I get a chance.

**Comment by Vmars666** [comment]
managed to fix it by myself , in filmauteur_ltxv.py ( i joined my fixed version of the node )


what i've done : 

Find this code (near the end of the process method, inside if decode:):

                if num_prompts > 1 and autoregressive_chunking:
                    print("--- Decoding Multi-Shot Audio Tracks ---")
                    ...
                    shot_wf = audio_vae.first_stage_model.decode(shot_a_latent).to(a_latent_samples.device)
                    
                    # Resample from 16kHz to 48kHz to fix the "Fast Playback" bug
                    shot_wf = torchaudio.functional.resample(shot_wf, sampling_rate, sample_rate)
                    ...
                else:
                    waveform = audio_vae.first_stage_model.decode(a_latent_samples).to(a_latent_samples.device)
                    # Resample from 16kHz to 48kHz
                    waveform = torchaudio.functional.resample(waveform, sampling_rate, sample_rate)


[filmauteur_ltxv.py](https://github.com/user-attachments/files/27104141/filmauteur_ltxv.py)

and remplace it with : 

                if num_prompts > 1 and autoregressive_chunking:
                    print("--- Decoding Multi-Shot Audio Tracks ---")
                    ...
                    shot_wf = audio_vae.first_stage_model.decode(shot_a_latent).to(a_latent_samples.device)
                    # No longer needed — LTX-2.3 VAE already outputs at correct sample rate
                    # shot_wf = torchaudio.functional.resample(shot_wf, sampling_rate, sample_rate)
                    ...
                else:
                    waveform = audio_vae.first_stage_model.decode(a_latent_samples).to(a_latent_samples.device)
                    # No longer needed — LTX-2.3 VAE already outputs at correct sample rate
                    # waveform = torchaudio.functional.resample(waveform, sampling_rate, sample_rate)




also  this a litte lower :      

           pristine_wf = torchaudio.functional.resample(master_wf.clone(), sampling_rate, sample_rate).to(waveform.device)

to : 

                # Use the ORIGINAL audio's native sample rate (not the VAE's)
                master_sr = master_wf.shape[-1] > 0 and getattr(audio, "sample_rate", 48000) if audio is not None else sampling_rate
                pristine_wf = torchaudio.functional.resample(master_wf.clone(), master_sr, sample_rate).to(waveform.device)

**Comment by triXope** [comment]
Awesome! Thanks so much. I'll take a look and make the merges to the main repo once I get back to my system.

**Comment by Vmars666** [comment]
you're welcome, you're node is cool you did a great work. 
just one thing, be careful ,the fix is used with ltx 2.3 but i'm not sure it would work with ltx 2.0 the problem was the frame rate difference in both models.
anyway thanks again and have a great day !

**Comment by triXope** [comment]
I just updated the node to clean up the code a bit and fix some other bug issues. Hopefully I've addressed everything. please update the node and take a look to see if you run into any other issues
